# frases para serem usadas no sistema

MSG_OPCAO_INVALIDA = "❌ Opção inválida! Por favor, escolha um número entre 0 e 5."
MSG_VOLTAR_MENU = "↩️ Pressione ENTER para voltar ao menu principal..."
MSG_LIVRO_CADASTRADO = "✅ Livro cadastrado com sucesso!"
MSG_LIVRO_NAO_ENCONTRADO = "⚠️ Livro não encontrado no acervo."
MSG_LEITOR_CADASTRADO = "✅ Leitor cadastrado com sucesso!"
MSG_EMPRESTIMO_REALIZADO = "📖 Empréstimo realizado com sucesso!"
MSG_DEVOLUCAO_REALIZADA = "🔄 Devolução processada com sucesso!"
MSG_MULTA_CALCULADA = "💰 Multa calculada: R$ {}"
MSG_ENCERRANDO = "👋 Encerrando o sistema. Até logo!"
MSG_DEVOLUCAO_ATRASADA = "⏰ Devolução com atraso! Multa será aplicada."
MSG_OPERACAO_CANCELADA = "⛔ Operação cancelada pelo usuário."
MSG_CONFIRMACAO_EXCLUSAO = "❓ Tem certeza que deseja excluir este registro? (S/N): "
MSG_LIVRO_EXISTENTE = "📕 Este livro já está cadastrado no sistema."
MSG_LEITOR_EXISTENTE = "👤 Este leitor já está cadastrado com este CPF/RM."
MSG_LIVRO_INDISPONIVEL = "🚫 Livro indisponível para empréstimo no momento."
MSG_LEITOR_NAO_ENCONTRADO = "⚠️ Leitor não encontrado na base de dados."
MSG_EMPRESTIMO_NAO_ENCONTRADO = "🔍 Nenhum empréstimo ativo encontrado para este leitor."
MSG_LIMITE_EMPRESTIMO_EXCEDIDO = "📚 Limite de empréstimos atingido (máximo de 3 obras por leitor)."
